#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import requests
import re
import sys
import os
from collections import Counter

os.system("export TO_LOG")
try:

    myString = sys.argv[1] # сайт
    word_list = sys.argv[2:]  # слова

    r = requests.get(myString)


#count = r. ext.count(word_str) #слова
    # print(count)

    words = re.findall(r'\w+', r.text) #все слова в список
    counter = Counter(words) # посчитали все слова, счетчик

    no_words = 0 # Если >0, то sys.exit(2)


    for word in word_list: # фильтрация

        count = r.text.count(word)
        no_words += count

        print(word, count)

        

            # print(logs)

    if os.environ["TO_LOG"] == "1":
        for word in word_list:
            count = r.text.count(word)
               
            with open("logs", 'a') as f:
                f.write(word + " " + str(count) + "\n")



except(OSError):
    # print("sys.exit(3)")
    sys.exit(3)
except:
    # print("sys.exit(1)")
    sys.exit(1)
if no_words == 0:
    # print("sys.exit(2)")
    sys.exit(2)
# print("sys.exit(0)")
sys.exit(0)

